# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='custom_css',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
